<html>
   <body>
      <html>
         <head>
            <?php
               echo '<title>My PHP Website Hosted on Convox</title>';
               ?>
         </head>
         <body>
            <?php
               echo '<p>This content was generated by PHP Code</p>';
               ?>
            <p>You are at a PHP website hosted using Convox.</p>
         </body>
      </html>
   </body>
</html>